### ISSUE TITLE
Kermit's Review

### ISSUE THREAD

**Issue by defoebrand** [eypsrcnuygr/HTML-Capstone#1]
Header
> Header link area should include text
> Maybe collapse header icons into more button

Search Form
> Search form buttons need spacing

Bottom Section
> Make images exact circles - consider img element
> Buttons need -y padding
> Bring elements closer together at larger widths

Footer
> Change wrapping property to keep icon more centered

Events Page
> Events images don't align - put two line titles on one line

Add one piece of code that you are particularly proud of and have spent time improving.

**Comment by eypsrcnuygr** [comment]
All suggested changes have been done.
